spring.application.name=beef

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://192.168.0.174:3306/beef?useSSL=false&allowPublicKeyRetrieval=true&useMysqlMetadata=true
spring.datasource.username=beef
spring.datasource.password=123456

logging.level.org.springframework=info
logging.level.org.zerock=debug

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080

api.naver.search.url=https://openapi.naver.com/v1/search/local.json
# NAVER MAP (JS ??)
naver.map.client.id=7sz4aehcd9

naver.search.client.id=XhyEMaKHUXSdckFVFAPv
naver.search.client.secret=_n7RPSwifq

# KAKAO LOCAL SEARCH (GPS ??)
kakao.rest.api.key=f454dc56718c506f49f645248d0988d8

# application.properties (또는 application.yml)
jwt.secret.key=QkY2RkYyODczMzk1NkREREM4RjZGNkY3OTg1NjEzNzY0MzQxMTU4Nzc1MzMxM0MyQTc4MkE4RDc0RkU3QzU5Ng==

spring.devtools.restart.enabled=false