buildscript {
    ext {
        queryDslVersion = "5.0.0"
    }
} /* 쿼리dsl 추가 설정 : p448쪽 */

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.12'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    /* 메이븐 리포지토리에서 코드를 가져와 코끼리를 누르면 가져온다. */

    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf' /* 프론트 관련 */
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.1.0' /* 프론트 레이아웃 관련*/
    implementation 'org.springframework.boot:spring-boot-starter-web'       /* string-web */

    // ⭐ 롬복 설정 (QueryDSL 에러 방지를 위해 위쪽 배치)
    compileOnly 'org.projectlombok:lombok'                                  /* 롬북 */
    annotationProcessor 'org.projectlombok:lombok'                          /* 롬북 */
    testCompileOnly 'org.projectlombok:lombok'                              /* 롬북 */
    testAnnotationProcessor 'org.projectlombok:lombok'                      /* 롬북 */

    /* DTO와 엔티티 간에 변환 처리용 P460 */
    implementation 'org.modelmapper:modelmapper:3.1.0'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'          /* boot 개발용 */

    /* 데이터 베이스 관련 */
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    /* 쿼리dsl 설정 */
    implementation "com.querydsl:querydsl-jpa:${queryDslVersion}:jakarta"
    annotationProcessor(
            "jakarta.persistence:jakarta.persistence-api",
            "jakarta.annotation:jakarta.annotation-api",
            "com.querydsl:querydsl-apt:${queryDslVersion}:jakarta"
    )

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.0'

    // Spring Security (로그인 및 비밀번호 암호화 기능)
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}

def querydslDir = "$buildDir/generated/querydsl"

sourceSets {
    main {
        java {
            srcDir querydslDir
        }
    }
}

// clean 태스크 실행 시 generated Q-Class 디렉토리를 삭제하도록 합니다.
tasks.named('clean') {
    delete file(querydslDir)
}

// 컴파일 시점에 QueryDSL Q-Class 생성이 먼저 되도록 의존성 설정
tasks.withType(JavaCompile).configureEach {
    options.generatedSourceOutputDirectory.set(file(querydslDir))
}
